### PR TITLE
Fix loading issue on IE11

### PR DESCRIPTION
**Pull request by lucatacconi**

### CODE REVIEW

**Comment by lucatacconi** [comment]
Fix issue  #83. As suggested i tried to invert lines xhr.open('GET', url); xhr.responseType = 'text'; 
It's OK on Chrome, Firefox, Chronium, Edge.. and it's OK also on IE11. 
I didn't try the loader on Safari and Opera

**Comment by hzsrc** [comment]
+1

**Comment by FranckFreiburger** [comment]
thanks for your fix

**Comment by NineSu** [comment]
I tried it, but it didn't work

**Pull request merged**
