### PR TITLE
Complete example added to readme

### PR DESCRIPTION
**Pull request by acklenx**
I added your example and comments from [issue 7](https://github.com/FranckFreiburger/http-vue-loader/issues/7) to the readme file.

### CODE REVIEW

**Comment by FranckFreiburger** [comment]
ping ?

**Comment by acklenx** [comment]
yes?

**Comment by FranckFreiburger** [comment]
do you see my code review in README.md ?

**Comment by acklenx** [comment]
I did not/do not... where should I be looking?  (In the reviewers section of this pull requests there are no reviewers listed... perhaps because you're the owner? I just don't know where to look.

**Comment by FranckFreiburger** [comment]
thanks

**Comment by acklenx** [comment]
No... thank you!

**Pull request merged**
